name: anbocas_tickets_api
description: Anbocas Tickets API to manage your events, tickets, company and all in one place
version: 0.0.1
homepage: https://github.com/anbocas/anbocas_tickets_api

environment:
  sdk: ">=3.1.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null
assets:
  - .env
