name: anbocas_tickets_api
description: Anbocas Tickets API to access platform APIs in Dart & Flutter projects.
version: 0.0.2
homepage: https://anbocas.com
documentation: https://anbocas.com
repository: https://github.com/anbocas/anbocas_tickets_api

environment:
  sdk: ">=3.1.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.4.3+1
  intl: ^0.19.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
